
name: gogoS3

on:
  push:
    branches: 
      - backend_deploy

jobs:
  deploy:
    name : setting_Os 
    runs-on: ubuntu-latest

    steps:
      - name : checkout
        uses: actions/checkout@v2
        
        # 자바 버전을 설정해준다.
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        
        # Gradle에 실행 권한을 부여한다.
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
        working-directory: ./backend
        
        # 빌드
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
        working-directory: ./backend
        
      # CodeDeploy를 사용하기 위해서는 S3를 거쳐야 한다. 따라서 압축된 파일을 만들어주고 이를 옮긴다.
      - name: Make zip file
        run: zip ./issue_tracker.zip ./cocomarco-0.0.1-SNAPSHOT.jar
        shell: bash
        working-directory: ./backend/build/libs
        
                # 인증 절차
      - name: deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_accesskey }}
          aws-secret-access-key: ${{ secrets.AWS_secretkey }}
          aws-region: ap-northeast-2
          
          #s3 업로드
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 --acl private ./issue_tracker.zip s3://coco-issue/
        working-directory: ./backend/build/libs
        
        
